import Link from "next/link";

export const metadata = {
  title: "Refund & Cancellation Policy",
  description:
    "Refund and cancellation terms for Whatly SaaS subscriptions.",
  alternates: { canonical: "/refund" },
};

export default function RefundPage() {
  return (
    <LegalLayout title="Refund & Cancellation Policy" lastUpdated="20 May 2026">
      <Section title="Free trial">
        Every new account gets a <strong>14-day free trial</strong>. No
        credit card required. After 14 days, the account freezes until you
        upgrade. <strong>No charges during the trial.</strong>
      </Section>

      <Section title="Subscription cancellation">
        You may cancel your paid subscription at any time from{" "}
        <strong>Settings → Billing → Cancel subscription</strong>.
        <ul className="list-disc pl-5 space-y-1 mt-2">
          <li>
            Service continues until the end of your current billing period.
          </li>
          <li>You won't be charged again.</li>
          <li>No cancellation fees or penalties.</li>
          <li>Your data is retained 90 days after cancellation, then deleted.</li>
        </ul>
      </Section>

      <Section title="Refund eligibility">
        <p className="mb-3">
          <strong>Within first 7 days of a paid period:</strong> Full refund
          on request, no questions asked. Email{" "}
          <a href="mailto:billing@example.com" className="underline">
            billing@example.com
          </a>{" "}
          with your account phone number.
        </p>
        <p className="mb-3">
          <strong>After 7 days:</strong> No prorated refunds. Service
          continues until period end. Cancel to prevent next charge.
        </p>
        <p>
          <strong>AI Add-on:</strong> Same 7-day rule. Unused AI credits do
          not carry over month-to-month.
        </p>
      </Section>

      <Section title="Razorpay payments">
        All payments are processed via Razorpay. Approved refunds are
        credited to your original payment method (UPI / card / netbanking)
        within <strong>5-7 working days</strong> of approval.
      </Section>

      <Section title="Customer-order payments">
        When your customers pay you (via Razorpay payment links generated by
        our platform), the funds settle directly to your Razorpay account.
        We do not hold customer funds. Refunds to your customers must be
        issued by you from your Razorpay dashboard.
      </Section>

      <Section title="Service issues">
        If the Service is unavailable for &gt; 24 hours due to our fault, we
        credit a prorated day to your next invoice. This is automatic — no
        request needed.
      </Section>

      <Section title="Plan downgrades">
        Downgrade anytime. New (lower) plan limits apply from next billing
        cycle. We do not refund the difference for the current period.
      </Section>

      <Section title="Fraud / policy violations">
        Accounts terminated for fraud, spam, or violation of our{" "}
        <Link href="/terms" className="underline">
          Terms
        </Link>{" "}
        are <strong>not eligible</strong> for refunds.
      </Section>

      <Section title="How to request a refund">
        Email <code>billing@example.com</code> with:
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Your account phone number</li>
          <li>Razorpay payment ID</li>
          <li>Reason (optional, helps us improve)</li>
        </ul>
        <p className="mt-2">We respond within 2 working days.</p>
      </Section>

      <Section title="Contact">
        Billing questions:{" "}
        <a href="mailto:billing@example.com" className="underline">
          billing@example.com
        </a>
        <br />
        WhatsApp:{" "}
        <a
          href="https://wa.me/919999999999"
          className="underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          +91 99999 99999
        </a>
      </Section>
    </LegalLayout>
  );
}


function LegalLayout({
  title,
  lastUpdated,
  children,
}: {
  title: string;
  lastUpdated: string;
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-white">
      <header className="border-b border-slate-100 px-4 py-4 sticky top-0 bg-white/95 backdrop-blur">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="w-8 h-8 rounded-lg bg-brand-500 text-white flex items-center justify-center">
              💬
            </span>
            <span className="font-bold text-slate-900">Whatly</span>
          </Link>
          <Link
            href="/"
            className="text-sm text-slate-600 hover:text-slate-900"
          >
            ← Back
          </Link>
        </div>
      </header>
      <article className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">{title}</h1>
        <p className="text-sm text-slate-500 mb-10">
          Last updated: {lastUpdated}
        </p>
        <div className="space-y-6 text-slate-700 leading-relaxed">
          {children}
        </div>
      </article>
    </main>
  );
}


function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-lg font-bold text-slate-900 mb-2">{title}</h2>
      <div className="text-sm">{children}</div>
    </section>
  );
}
